### ISSUE TITLE
Interface Dupe Bug

### ISSUE THREAD

**Issue by Zerosk83** [raoulvdberge/refinedstorage#1228]
#### Issue description: 
Items can be duped at will, and non-stackable items can be forced to stack

#### What happens: 
Changing the item filter in the interface causes and existing items inside of that same type, to be converted into the "new" filtered item.

#### What you expected to happen: 
No dupe.

#### Steps to reproduce: 
This youtube video shows the exact steps. 
https://www.youtube.com/watch?v=g6wlwpAQHvA

For anyone who can't watch, basically you put a stack of anything inside the storage system, then open the interface and add an item to the filter list, then add 1 of that item to the Interface's inventory (top bar). The Interface will move this item to the bottom bar (because of the filter setting). Without removing the item from the bottom bar, change the filtered item to the item you wish to dupe. The system will convert the bottom bar item into a stack the new duped item, removing the original stack of items you put in the system at first. So you can convert a stack of cobble into a stack of anything at will, as long as you have 1 of that item to start with. 

#### Version (make sure you are on the latest version before reporting): 
1.2.25 (This is the latest version for 1.10.2. It also the default version used in FTB Beyond)

- Minecraft: 1.10.2 (FTB Beyond)
- Forge: 12.18.3.2281
- Refined Storage: 1.2.25

Does this issue occur on a server? [yes/no] 
Yes (tested it on my own server after watching the video)

#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by raoulvdberge** [comment]
Duplicate of:
- #1206
- #892 

Fixed for 1.11. Will come to 1.10.2 soon as well.

**Comment by heyoomimi** [comment]
Has this been pushed to 1.10.2 yet?

**Comment by raoulvdberge** [comment]
1.10 is unsupported.

**Comment by heyoomimi** [comment]
Then you shouldn't have stated that it was fixed in the 1.2.26 changelog.

**Comment by raoulvdberge** [comment]
It was fixed when I tested it.

**Comment by heyoomimi** [comment]
Okay thank you for your quick response, we'll continue to investigate the problem on our end. Although, it may be worth keeping in mind that the mod is not fixed for 1.10.2.
