### ISSUE TITLE
Crash with JEI 3.11.0.269

### ISSUE THREAD

**Issue by FnordMan** [raoulvdberge/refinedstorage#383]
#### Issue description:
Crash upon entering world with refined storage 1.0.5 and JEI 3.11.0.269 installed. 
Downgrading JEI to v3.10.0.268 fixes the problem. 

#### Version (Make sure you are on the latest version before reporting):

- Minecraft: 1.10.2
- Forge: 2089
- Refined Storage: 1.0.5

Does this issue occur on a server? [yes/no]

#### If a (crash)log is relevant for this issue, link it here:

[fml-client-latest.txt](https://github.com/raoulvdberge/refinedstorage/files/491736/fml-client-latest.txt)

**Comment by raoulvdberge** [comment]
Fixed for the next version coming within 1-2 days

**Comment by AlphaKintari** [comment]
JEI 3.11.1.270 does not resolve the issue. Might need to wait for another update.
http://paste.ee/p/962iq

**Comment by raoulvdberge** [comment]
I meant an Refined Storage update, not a JEI update.

**Comment by AlphaKintari** [comment]
figured that after the last few JEI updates. ;) 
Thanks!
