### ISSUE TITLE
Pattern that use ore dictionary is not function properly

### ISSUE THREAD

**Issue by oks1998** [raoulvdberge/refinedstorage#796]
When I try to craft a steel machine block from mekanism using the pattern that I created with enabled use ore dictionary, it just can't auto make the ingredient that require.

There is IC2 steel ingot (it call Refined Iron ingot but is actually Steel Ingot in the waila) and mekanism steel ingot, when the storage got mekanism ingot at least 1, system can auto make the rest of require amount with the pattern I set before, but if the system contain 0 ingot of mekanism steel ingot, it will show that system require IC2 Refined Iron ingot even though the recipe I set for Steel Machine Block is using mekanism Ingot with enabled ore dictionary.

I espect that the system will find the correspond recipe for the steel ingot (as long as the ingot is in "Steel" category of the dictionary and make the Steel machine block automatically. When system found out there is no steel ingot in the system, find a steel ingot recipe, if found the recipe is in "steel category" aka ore dictioanary, then make that as the ingredient.

- Minecraft: 1.10.2
- Forge: forge-12.18.3.2185
- Refined Storage: refinedstorage-1.2.14

[photos:](http://imgur.com/a/77m1h)

**Comment by devanchya** [comment]
This may explain why I can't create pistons now.

**Comment by way2muchnoise** [comment]
Should be all fixed as of 6fdff3e0f70301a2ba590f5e6483ef254fe65ee7

**Comment by oks1998** [comment]
I updated to refined Storage 1.2.15 but the problem still exist.

Either with Both type of Steel Ingot with or without Ore Dictionary enabled, all cannot use existing steel ingot recipe to craft the require amount of steel ingot

**Comment by way2muchnoise** [comment]
Seems like I missed a flag change. But previous commit should fix that. Guess we'll have to do a 1.2.16 soon™

**Comment by devanchya** [comment]
I noticed that this might be an issue with the patern encoder and the
resource stand alone block.   You can test if it is working by creating a
piston and trying other wood planks.

Suggestion. Make the resource process pattern containers look different
after creation?
